# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5340eaec36dfefd4ebfe8a52d450938b4dadef86e86edcd2e9366d19b05943de1eabd56df5044a329431ab828edbf53a774bd742afb78a99f4553a175fabef4

test:
  secret_key_base: 8c1e1a6e6a4e837344531d7333a28ded8415af5e26b01ffa1854da407591ca53eca386ed74b8dde60936fbeab55d69a6358ea07c623738d6efdd1c5829c674ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
